import type {Jet} from "./jets.types";

const img = "/images/jets/placeholder.svg";
const doc = (id: string) => `https://example.com/docs/${id}`;
const order = (id: string) => `https://example.com/order/${id}`;

export const jetsCatalog: Jet[] = [
    {
        id: "citation_m2",
        title: "Cessna Citation M2",
        manufacturer: "Cessna",
        category: "very_light",
        summary: "Compact jet for quick regional trips with low operating costs.",
        description: "Entry-level private jet designed for efficient regional hops. Great for small teams and shorter runways.",
        rangeKm: 2870,
        seats: 6,
        speedKmh: 748,
        priceEstimateUsd: 5_500_000,
        tags: ["compact", "efficient", "regional"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Cessna_Citation_M2.jpg?width=500",
        docsUrl: doc("citation_m2"),
        orderUrl: order("citation_m2"),
    },
    {
        id: "pc24",
        title: "Pilatus PC-24",
        manufacturer: "Pilatus",
        category: "utility",
        summary: "A versatile jet that’s comfortable with shorter runways.",
        description: "A rugged, flexible jet often chosen for hard-to-reach destinations. Balances cabin space with practical runway performance.",
        rangeKm: 3700,
        seats: 8,
        speedKmh: 815,
        priceEstimateUsd: 10_500_000,
        tags: ["short-runway", "versatile", "utility"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Pilatus_PC-24_prototype_rollout.jpg?width=500",
        docsUrl: doc("pc24"),
        orderUrl: order("pc24"),
    },
    {
        id: "phenom_300e",
        title: "Embraer Phenom 300E",
        manufacturer: "Embraer",
        category: "light",
        summary: "Popular light jet with strong speed and cabin comfort.",
        description: "A widely used light jet for business travel. Strong mix of speed, comfort, and range in its class.",
        rangeKm: 3650,
        seats: 9,
        speedKmh: 839,
        priceEstimateUsd: 11_000_000,
        tags: ["popular", "fast", "light-jet"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Embraer_Phenom_300E_exterior.jpg?width=500",
        docsUrl: doc("phenom_300e"),
        orderUrl: order("phenom_300e"),
    },
    {
        id: "citation_cj4",
        title: "Cessna Citation CJ4",
        manufacturer: "Cessna",
        category: "light",
        summary: "Reliable light jet with extended range for its class.",
        description: "Well-known light jet used for business and owner-operators. Solid range and a comfortable cabin layout.",
        rangeKm: 4000,
        seats: 9,
        speedKmh: 839,
        priceEstimateUsd: 10_000_000,
        tags: ["reliable", "light-jet", "range-focused"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Cessna_Citation_CJ4_N543TX_FDK_MD1.jpg?width=500",
        docsUrl: doc("citation_cj4"),
        orderUrl: order("citation_cj4"),
    },
    {
        id: "praetor_600",
        title: "Embraer Praetor 600",
        manufacturer: "Embraer",
        category: "midsize",
        summary: "Super-capable midsize jet with long legs and modern cabin.",
        description: "Midsize jet optimized for longer missions. Strong range and a modern cabin make it a flexible choice for multi-city travel.",
        rangeKm: 7400,
        seats: 12,
        speedKmh: 863,
        priceEstimateUsd: 21_000_000,
        tags: ["long-range", "modern", "midsize"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Preator_600.jpg?width=500",
        docsUrl: doc("praetor_600"),
        orderUrl: order("praetor_600"),
    },
    {
        id: "challenger_3500",
        title: "Bombardier Challenger 3500",
        manufacturer: "Bombardier",
        category: "super_midsize",
        summary: "A super-midsize workhorse with premium cabin and solid range.",
        description: "A refined super-midsize jet with a comfortable cabin and strong cross-continent capability.",
        rangeKm: 5900,
        seats: 10,
        speedKmh: 870,
        priceEstimateUsd: 26_000_000,
        tags: ["workhorse", "super-midsize", "comfort"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Ryanair_M-ABSU_Bombardier_Challenger_3500_EMA_25-05-2025.jpg?width=500",
        docsUrl: doc("challenger_3500"),
        orderUrl: order("challenger_3500"),
    },
    {
        id: "g280",
        title: "Gulfstream G280",
        manufacturer: "Gulfstream",
        category: "super_midsize",
        summary: "Fast super-midsize jet with strong transcontinental range.",
        description: "Super-midsize jet known for speed and range. A strong choice for efficient coast-to-coast missions.",
        rangeKm: 6675,
        seats: 10,
        speedKmh: 900,
        priceEstimateUsd: 24_000_000,
        tags: ["fast", "super-midsize", "coast-to-coast"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Gulfstream_G280_N82CW_FDK_MD1.jpg?width=500",
        docsUrl: doc("g280"),
        orderUrl: order("g280"),
    },
    {
        id: "falcon_2000lxs",
        title: "Dassault Falcon 2000LXS",
        manufacturer: "Dassault",
        category: "heavy",
        summary: "Heavy jet comfort with strong range and a spacious cabin.",
        description: "A comfortable heavy jet with a spacious cabin. Well-suited for longer international missions with premium comfort.",
        rangeKm: 7400,
        seats: 10,
        speedKmh: 850,
        priceEstimateUsd: 35_000_000,
        tags: ["heavy-jet", "spacious", "premium"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/CAT_Aviation%2C_HB-IGO%2C_Dassault_Falcon_2000LXS_%2849580843472%29.jpg?width=500",
        docsUrl: doc("falcon_2000lxs"),
        orderUrl: order("falcon_2000lxs"),
    },
    {
        id: "g500",
        title: "Gulfstream G500",
        manufacturer: "Gulfstream",
        category: "heavy",
        summary: "Long-range heavy jet for high-comfort business travel.",
        description: "Heavy jet optimized for longer routes with a high-comfort cabin. A balanced option between range and price in the heavy segment.",
        rangeKm: 9630,
        seats: 14,
        speedKmh: 900,
        priceEstimateUsd: 48_000_000,
        tags: ["long-range", "luxury", "heavy-jet"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Gulfstream_G500_N1980G_FDK_MD1.jpg?width=500",
        docsUrl: doc("g500"),
        orderUrl: order("g500"),
    },
    {
        id: "falcon_8x",
        title: "Dassault Falcon 8X",
        manufacturer: "Dassault",
        category: "ultra_long_range",
        summary: "Ultra long-range jet with premium cabin and strong efficiency.",
        description: "Ultra long-range jet designed for intercontinental routes. Known for comfort, range, and operational flexibility.",
        rangeKm: 11945,
        seats: 16,
        speedKmh: 900,
        priceEstimateUsd: 58_000_000,
        tags: ["ultra-long-range", "intercontinental", "premium"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Dassault_Falcon_8X.jpg?width=500",
        docsUrl: doc("falcon_8x"),
        orderUrl: order("falcon_8x"),
    },
    {
        id: "g650er",
        title: "Gulfstream G650ER",
        manufacturer: "Gulfstream",
        category: "ultra_long_range",
        summary: "Iconic ultra long-range jet built for top-tier comfort and speed.",
        description: "Ultra long-range jet built for global missions. High speed, large cabin, and premium comfort for long-haul travel.",
        rangeKm: 13890,
        seats: 18,
        speedKmh: 982,
        priceEstimateUsd: 70_000_000,
        tags: ["ultra-long-range", "fast", "luxury"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/Gulfstream_G650ER_%2827707963891%29.jpg?width=500",
        docsUrl: doc("g650er"),
        orderUrl: order("g650er"),
    },
    {
        id: "global_7500",
        title: "Bombardier Global 7500",
        manufacturer: "Bombardier",
        category: "ultra_long_range",
        summary: "Top-tier range and cabin space for true intercontinental missions.",
        description: "Ultra long-range flagship jet with excellent range and cabin space. Built for long-haul travel with multiple living zones.",
        rangeKm: 14260,
        seats: 19,
        speedKmh: 982,
        priceEstimateUsd: 75_000_000,
        tags: ["ultra-long-range", "flagship", "spacious"],
        imagePath: "https://commons.wikimedia.org/wiki/Special:FilePath/9H-VIC_%2851402453773%29.jpg?width=500",
        docsUrl: doc("global_7500"),
        orderUrl: order("global_7500"),
    },
];